name: JS Actions

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  add-comment:
    if: github.event.label.name == 'joke wanted'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Get a new joke
        id: joke
        uses: ./.github/actions/joke-action
      - name: Display Joke
        run: echo "joke is ${{ steps.joke.outputs.joke-output }}"  
      - name: Print Output
        id: output
        run: echo "${{ steps.joke.outputs.joke-output }}"
      

      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            I know you are busy but here is a little joke to make you **smile!**
            :sparkles: ${{ steps.joke.outputs.joke-output }} :sparkles:
