name: JS Actions

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  add-comment:
    if: github.event.label.name == 'joke wanted'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: ha-ha
        uses: ./.github/actions/joke-action
      - name: Display Joke
        run: echo "joke is ${{ steps.hi-ha.outputs.joke-output }}"  
      

      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is available for anyone to work on.
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:
